name: Shadow Clojurescript CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3.7.0
    - name: Install shadow-cljs
      run: npx install shadow-cljs
    - name: Run tests
      run: npx shadow-cljs compile node-test
